<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../LeitorDeNotas.ClearArch.Commons/LeitorDeNotas.ClearArch.Commons.csproj" />
    <ProjectReference Include="..\LeitorDeNotas.ClearArch.Application\LeitorDeNotas.ClearArch.Application.csproj" />
    <ProjectReference Include="..\LeitorDeNotas.ClearArch.Infrastructure\LeitorDeNotas.ClearArch.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Openapi" Version="1.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.2" />
  </ItemGroup>
</Project>
