<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.5.0" />
    <PackageReference Include="xunit" Version="2.6.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.6.2" />
    <PackageReference Include="Moq" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\LeitorDeNotas.ClearArch.Application\LeitorDeNotas.ClearArch.Application.csproj" />
    <ProjectReference Include="..\..\src\LeitorDeNotas.ClearArch.Domain\LeitorDeNotas.ClearArch.Domain.csproj" />
  </ItemGroup>
</Project>
